version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./project:/var/www/html/project
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - webnet
  php:
    image: php:v1
    volumes:
      - ./project:/var/www/html/project
    networks:
      - webnet

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web
      MYSQL_USER: web
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - /root/docker-compose/lnmp/mysql/data:/var/lib/mysql  # 数据挂载目录
      - /root/docker-compose/lnmp/mysql/config/my.cnf:/etc/mysql/my.cnf  # 配置文件挂载
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
